name: todo_app
services:
    ngnix:
         image: nginx:alpine
         restart: unless-stopped
         ports:
         - 8000:80
         volumes: 
         - ./:/var/www
         networks:
            - todo_app-networks
         

    app:
        build:
        context: ./
        dockerfile: Dockerfile
        container_name: todo_app
        restart: unless-stopped
        working_dir : /var/www
        volumes:
            -./:/var/www
        networks:
            - todo_app-networks


    db:
        image: mysql:5.6
        container_name: todo_app
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pwd 
            - MYSQL_USER=${db_username}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATAABSE=${DB_DATABASE}
        ports:
            -3606:3606
        volumes:
            -

        networks:
            todo_app-networks:
            driver: bridge
            name: todo_app-networks
        volumes:
            todo_app_db_volume: